apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |   
    - userarn: arn:aws:iam::342203237813:user/vyshak-user
      username: vyshak-user
      groups:
        - system:masters

